export type Locale = "ko" | "en";
export type StringEntry = { ko: string; en: string; notes?: string };

export const strings = {
  // ───── Meta ─────
  "meta.title":            { ko: "Friend-Rating · 친구 평가", en: "Friend-Rating · Rate Your Friends" },
  "meta.description":      { ko: "친구한테 익명으로 솔직한 평가 받기 — 인스타 스토리로 공유하세요.", en: "Get honest anonymous ratings from your friends — share to your Instagram story." },
  "meta.lookup.title":     { ko: "내 통지표 조회 · Friend-Rating", en: "Check My Report Card · Friend-Rating" },
  "meta.rateStart.title":  { ko: "평가하러 왔어요 · Friend-Rating", en: "Here to Rate · Friend-Rating" },

  // ───── Common ─────
  "common.badge":                    { ko: "FRIEND-RATING", en: "FRIEND-RATING" },
  "common.nav.home":                 { ko: "← 홈", en: "← Home" },
  "common.nav.back":                 { ko: "← 이전", en: "← Back" },
  "common.preview.footer":           { ko: "2026 · Friend-Rating 프리뷰", en: "2026 · Friend-Rating Preview" },
  "common.error.network":            { ko: "네트워크 오류", en: "Network error" },
  "common.error.unknown":            { ko: "알 수 없는 오류", en: "Unknown error" },
  "common.toast.link.copied":        { ko: "링크 복사됐어요! 친구한테 보내봐 🔗", en: "Link copied! Send it to your friends 🔗" },
  "common.toast.link.copyFailed":    { ko: "복사 실패 — 주소창에서 직접", en: "Copy failed — grab from URL bar" },
  "common.toast.link.copyFailedLong":{ ko: "복사 실패 — 주소창에서 직접 복사해주세요", en: "Copy failed — please copy from the URL bar" },
  "common.empty.title":              { ko: "아직 아무도 평가를 안 남겼어요", en: "Nobody's rated you yet" },
  "common.empty.body":               { ko: "@{id} 아직 평가가 없어요.\n링크를 친구한테 뿌려보세요!", en: "No reviews for @{id} yet.\nShare your link with friends first!" },
  "common.empty.cta.copyLink":       { ko: "친구한테 평가 부탁하기 🔗", en: "Ask friends to rate me 🔗" },
  "common.empty.footer.onePublic":   { ko: "1건만 쌓여도 바로 여기서 보여요", en: "Just 1 review and it shows up here" },

  // ───── Landing ─────
  "landing.headline.full":           { ko: "친구한테 {highlight}\n받아볼 시간", en: "Time to get {highlight}\nfrom your friends" },
  "landing.headline.highlight":      { ko: "솔직한 평", en: "honest ratings" },
  "landing.sub":                     { ko: "익명 평가 · 가입 없음 — **1건만 쌓여도 바로 공개**.", en: "Anonymous · no signup — **public with just 1 review**." },
  "landing.cta.host.sticker":        { ko: "HOST", en: "HOST" },
  "landing.cta.host.label":          { ko: "I'M THE HOST", en: "I'M THE HOST" },
  "landing.cta.host.title":          { ko: "내 통지표 조회하기", en: "Check my report card" },
  "landing.cta.host.sub":            { ko: "내 아이디로 친구들이 남긴 평가 보기", en: "See the ratings your friends left for you" },
  "landing.cta.guest.sticker":       { ko: "GUEST", en: "GUEST" },
  "landing.cta.guest.label":         { ko: "I'M A GUEST", en: "I'M A GUEST" },
  "landing.cta.guest.title":         { ko: "누구 평가하러 왔어요", en: "Here to rate someone" },
  "landing.cta.guest.sub":           { ko: "상대 아이디로 익명 평가 남기기", en: "Rate a friend anonymously" },
  "landing.hero.alt":                { ko: "폰으로 친구 통지표를 보는 일러스트", en: "Illustration of friends looking at a report card" },
  "landing.info.noSignup":           { ko: "**가입 없음**. 인스타 아이디만 있으면 바로 통지표예요.", en: "**No signup**. Just your Instagram handle and you've got a report card." },
  "landing.info.anonymous":          { ko: "**완전 익명**이니까 솔직하게 써도 돼요. 누가 썼는지 호스트도 영영 몰라요.", en: "**Fully anonymous** — go ahead and be honest. Even the host will never know who wrote what." },
  "landing.info.sharing":            { ko: "평가 1건만 들어와도 **바로 공개**. 인스타 스토리용 카드 이미지로 내려받을 수 있어요.", en: "**Public from the first review**. Download as a card image for your Instagram story." },

  // ───── Lookup ─────
  "lookup.headline":                 { ko: "내 통지표 {highlight}", en: "{highlight} my report card" },
  "lookup.headline.highlight":       { ko: "조회하기", en: "Check" },
  "lookup.nav.badge":                { ko: "통지표 조회", en: "View report card" },
  "lookup.sub":                      { ko: "내 아이디만 입력하면\n친구들이 남긴 평가가 바로 보여요.", en: "Just enter your handle —\nwe'll show all the ratings your friends left." },
  "lookup.field.instaId.label":      { ko: "내 인스타 아이디", en: "Your Instagram handle" },
  "lookup.field.instaId.placeholder":{ ko: "내 아이디", en: "your_handle" },
  "lookup.field.birth.label":        { ko: "생년월일 6자리", en: "Birthday (6 digits)" },
  "lookup.field.birth.hint":         { ko: "(예: 940530)", en: "(e.g. 940530)" },
  "lookup.field.birth.placeholder":  { ko: "······", en: "······" },
  "lookup.field.birth.footer":       { ko: "아이디 + 생일 조합이 곧 통지표 하나예요. 서버엔 해시로만 저장돼요.", en: "Handle + birthday = one report card. Stored as a hash only." },
  "lookup.submit.idle":              { ko: "내 통지표 열기", en: "Open my report card" },
  "lookup.submit.loading":           { ko: "조회 중…", en: "Looking up…" },
  "lookup.error.queryFailed":        { ko: "조회 실패: {msg}", en: "Lookup failed: {msg}" },

  // ───── RateStart ─────
  "rateStart.headline":              { ko: "누구 {highlight} 왔어요?", en: "Who are you here to {highlight}?" },
  "rateStart.headline.highlight":    { ko: "평가하러", en: "rate" },
  "rateStart.nav.badge":             { ko: "평가하러 왔어요", en: "Here to rate" },
  "rateStart.sub":                   { ko: "상대 인스타 아이디만 있으면 OK.\n가입 없이 바로 **익명 평가** 남길 수 있어요.", en: "Just need their Instagram handle.\nNo signup — leave an **anonymous review** right away." },
  "rateStart.field.instaId.label":   { ko: "상대 인스타 아이디", en: "Their Instagram handle" },
  "rateStart.field.instaId.placeholder": { ko: "insta_handle", en: "insta_handle" },
  "rateStart.field.instaId.hint":    { ko: "아이디는 영문, 숫자, `.`, `_`만 가능해요.", en: "Only letters, numbers, `.`, `_` allowed." },
  "rateStart.submit":                { ko: "평가 남기러 가기 →", en: "Go write a review →" },

  // ───── Verify ─────
  "verify.card.label":               { ko: "RATE · THIS · FRIEND", en: "RATE · THIS · FRIEND" },
  "verify.card.question":            { ko: "이 친구 맞나요?", en: "Is this the one?" },
  "verify.card.sticker":             { ko: "FRIEND", en: "FRIEND" },
  "verify.nav.badge":                { ko: "평가하러 왔어요", en: "Here to rate" },
  "verify.field.birth.label":        { ko: "친구 인증", en: "Friend verification" },
  "verify.field.birth.hint":         { ko: "(당신이 아는 @{id}의 생일 6자리)", en: "(The @{id} birthday you know — 6 digits)" },
  "verify.hint.toggle.closed":       { ko: "생일 왜 필요해요? 🤔", en: "Why the birthday? 🤔" },
  "verify.hint.toggle.open":         { ko: "알겠어요, 접을게요", en: "Got it, collapse" },
  "verify.hint.1":                   { ko: "**1.** 진짜 친구만 평가할 수 있게 하는 살짝 허들이에요.", en: "**1.** A tiny gate so only real friends can review." },
  "verify.hint.2":                   { ko: "**2.** 같은 아이디여도 생일이 다르면 {separated}로 분리돼요.", en: "**2.** Same handle with a different birthday creates a {separated}." },
  "verify.hint.2.separated":         { ko: "완전 별개 통지표", en: "totally separate report card" },
  "verify.hint.3":                   { ko: "**3.** 서버엔 해시로만 저장, 호스트도 누가 썼는지 영영 몰라요.", en: "**3.** Stored as a hash only — even the host never learns who wrote what." },
  "verify.footer":                   { ko: "2B 프리뷰 · 인증 화면", en: "2B preview · Verify screen" },
  "verify.submit":                   { ko: "평가 남기러 가기", en: "Go write a review" },

  // ───── RateForm ─────
  "rateForm.nav.badge":              { ko: "평가 작성", en: "Write review" },
  "rateForm.target.label":           { ko: "RATING", en: "RATING" },
  "rateForm.axis.humor.label":       { ko: "유머감각", en: "Humor" },
  "rateForm.axis.humor.sub":         { ko: "같이 있으면 웃기나요?", en: "Do they crack you up?" },
  "rateForm.axis.humor.low":         { ko: "진지맨", en: "Too serious" },
  "rateForm.axis.humor.high":        { ko: "웃음 폭발", en: "Non-stop laughs" },
  "rateForm.axis.loyalty.label":     { ko: "의리", en: "Loyalty" },
  "rateForm.axis.loyalty.sub":       { ko: "믿을 수 있나요?", en: "Can you count on them?" },
  "rateForm.axis.loyalty.low":       { ko: "슬쩍 배신", en: "Kinda shady" },
  "rateForm.axis.loyalty.high":      { ko: "철벽 의리", en: "Ride or die" },
  "rateForm.axis.texting.label":     { ko: "연락", en: "Texting" },
  "rateForm.axis.texting.sub":       { ko: "연락은 잘 되나요?", en: "Do they actually reply?" },
  "rateForm.axis.texting.low":       { ko: "읽씹 장인", en: "Serial ghoster" },
  "rateForm.axis.texting.high":      { ko: "답장 빠름", en: "Always replies" },
  "rateForm.axis.vibes.label":       { ko: "바이브", en: "Vibes" },
  "rateForm.axis.vibes.sub":         { ko: "같이 있으면 어때요?", en: "How do you feel around them?" },
  "rateForm.axis.vibes.low":         { ko: "에너지 방전", en: "Energy drain" },
  "rateForm.axis.vibes.high":        { ko: "에너지 충전", en: "Energy boost" },
  "rateForm.axis.secrets.label":     { ko: "비밀유지", en: "Secrets" },
  "rateForm.axis.secrets.sub":       { ko: "비밀을 지키나요?", en: "Can they keep a secret?" },
  "rateForm.axis.secrets.low":       { ko: "소문 전파기", en: "Tells everyone" },
  "rateForm.axis.secrets.high":      { ko: "비밀 금고", en: "Vault locked" },
  "rateForm.comment.title":          { ko: "마지막으로 남기고 싶은 말", en: "One last thing to say" },
  "rateForm.comment.sub":            { ko: "한 줄이어도 OK. 익명이니까 진심 툭~", en: "One line is fine. You're anon, just say it" },
  "rateForm.comment.placeholder":    { ko: "예) 같이 있으면 진짜 편해~ 근데 연락은 좀 해줘 ㅋㅋ", en: "e.g. Super fun to hang with, just reply to my texts lol" },
  "rateForm.comment.counter":        { ko: "{len}/{max}", en: "{len}/{max}" },
  "rateForm.avgPreview.label":       { ko: "내가 준 평균", en: "My avg" },
  "rateForm.avgPreview.unit":        { ko: "/ 5.0", en: "/ 5.0" },
  "rateForm.submit.idle":            { ko: "익명으로 통지표 전송하기", en: "Send anonymously" },
  "rateForm.submit.loading":         { ko: "전송 중…", en: "Sending…" },
  "rateForm.submit.warning":         { ko: "제출하면 수정 · 삭제가 어려워요. 한 번만 꾸욱.", en: "No edits or deletes after submit. One firm tap." },
  "rateForm.error.rateLimit":        { ko: "바로 전에 같은 네트워크에서 평가가 올라갔어요. 5분 뒤 다시 시도해주세요.", en: "Same network just submitted. Try again in 5 minutes." },
  "rateForm.error.submitFailed":     { ko: "제출 실패: {err}", en: "Submit failed: {err}" },
  "rateForm.success.title":          { ko: "익명 평가 전송 완료!", en: "Anonymous review sent!" },
  "rateForm.success.sticker":        { ko: "SENT!", en: "SENT!" },
  "rateForm.success.msg":            { ko: "**@{id}** 님의 통지표에 당신의 {avgBold} 평가가 쏙 들어갔어요.", en: "Your {avgBold} review slipped into **@{id}**'s report card." },
  "rateForm.success.msg.avg":        { ko: "{avg}점", en: "{avg}-star" },
  "rateForm.success.shushing":       { ko: "누가 썼는지 아무도 몰라요", en: "No one knows who wrote it" },
  "rateForm.success.cta.view":       { ko: "@{id} 통지표 구경하기", en: "Peek at @{id}'s report card" },
  "rateForm.success.cta.home":       { ko: "홈으로 돌아가기", en: "Back to home" },
  "rateForm.success.footer":         { ko: "2C 프리뷰 · 완료 화면", en: "2C preview · Done screen" },

  // ───── Dashboard ─────
  "dashboard.card.label":            { ko: "MY.REPORT.CARD", en: "MY.REPORT.CARD" },
  "dashboard.title":                 { ko: "{idChip} 님의\n{highlight} 통지표!", en: "{idChip}'s\n{highlight} report card!" },
  "dashboard.title.highlight":       { ko: "찐친 공인", en: "certified" },
  "dashboard.stats":                 { ko: "총 {countBold}이 평가했어요 · 평균 {avgBold} / 5.0", en: "{countBold} have rated · avg {avgBold} / 5.0" },
  "dashboard.stats.count":           { ko: "{count}명", en: "{count} people" },
  "dashboard.axis.humor":            { ko: "유머감각", en: "Humor" },
  "dashboard.axis.loyalty":          { ko: "의리", en: "Loyalty" },
  "dashboard.axis.texting":          { ko: "연락", en: "Texting" },
  "dashboard.axis.vibes":            { ko: "바이브", en: "Vibes" },
  "dashboard.axis.secrets":          { ko: "비밀유지", en: "Secrets" },
  "dashboard.comments.title":        { ko: "마지막 한마디 모음집", en: "Last words collection" },
  "dashboard.comments.empty.title":  { ko: "주관식 코멘트는 아직 없어요", en: "No written comments yet" },
  "dashboard.comments.empty.sub":    { ko: "평가는 남겼는데 말은 없었던 친구가 있나봐요 🤐", en: "Some friends rated but stayed quiet 🤐" },
  "dashboard.cta.share.label":       { ko: "내 통지표 인스타에 뿌리러 가기", en: "Flex this report card on Instagram" },
  "dashboard.cta.share.sticker":     { ko: "SHARE", en: "SHARE" },
  "dashboard.cta.copy":              { ko: "친구한테 평가 부탁하기!", en: "Ask friends to rate me!" },
  "dashboard.cta.copy.done":         { ko: "복사됐어요! 친구한테 보내줘 🎉", en: "Copied! Send it to your friends 🎉" },
  "dashboard.state.loading":         { ko: "통지표 가져오는 중…", en: "Fetching report card…" },
  "dashboard.state.missing.title":   { ko: "로그인 정보가 없어요", en: "Missing login info" },
  "dashboard.state.missing.sub":     { ko: "홈에서 아이디로 들어와주세요.", en: "Head home and enter your handle." },
  "dashboard.state.missing.cta":     { ko: "홈으로 가기", en: "Go home" },
  "dashboard.state.notfound.title":  { ko: "아직 평가가 없어요", en: "No ratings yet" },
  "dashboard.state.notfound.body":   { ko: "**@{id}** 아직 평가가 없어요.\n링크를 친구한테 뿌려보세요!", en: "No ratings for **@{id}** yet.\nShare the link with your friends!" },
  "dashboard.state.notfound.bodyNoId": { ko: "아이디를 다시 확인해주세요.", en: "Please double-check your handle." },
  "dashboard.state.notfound.cta.home": { ko: "홈으로 돌아가기", en: "Back to home" },
  "dashboard.state.error.title":     { ko: "불러오는 중 문제가 생겼어요", en: "Something went wrong while loading" },
} as const satisfies Record<string, StringEntry>;

export type StringKey = keyof typeof strings;

export function t(
  key: StringKey,
  vars?: Record<string, string | number>,
  locale: Locale = "ko",
): string {
  const entry = strings[key];
  const raw = entry[locale] || entry.ko;
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (m, name: string) =>
    name in vars ? String(vars[name]) : m,
  );
}
